name: GitHub Actions Phpsecure
on:
  push:
    branches:
      - master
jobs:
  Phpsecure-Action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Phpsecure Vulnerabilities Scanner
        uses: PhpSecureScanner/phpsecure_action@v0.1.6
        env:
          PHPSECURE_AUTH_TOKEN: ${{ secrets.PHPSECURE_AUTH_TOKEN }}
          
