name: GitHub Actions Phpsecure
run-name: ${{ github.actor }} is testing Phpsecure Action 🚀
on: [push]
jobs:
  Phpsecure-Action:
    runs-on: ubuntu-latest
    steps:
      - name: Phpsecure Vulnerabilities Scanner
        uses: PhpSecureScanner/phpsecure_action@v0.1

