name: GitHub Actions Phpsecure
run-name: ${{ github.actor }} is testing Phpsecure Action 🚀
on: [push]
jobs:
  Phpsecure-Action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Phpsecure Vulnerabilities Scanner
        uses: PhpSecureScanner/phpsecure_action@v0.1.5
        env:
          PHPSECURE_AUTH_TOKEN: ${{ secrets.PHPSECURE_AUTH_TOKEN }}
          INPUT_PROJECT_NAME: "github test"

